### ISSUE TITLE
Weariverse Tab

### ISSUE THREAD

**Issue by drGrove** [lrvick/wearscript-playground#11]
weariverse tab and new gists view (redone version of weariverse and gists list as the same codebase).  Weariverse part can be accessed from a URL that hides menu by default until you try to use something that requires playground

**Comment by bwhite** [comment]
Should have link to open in playground, description, (trim off the [wearscript]), and optionally (for your own gists) a button to submit them to weariverse (can be toggled, I'll have a way to query the state later)

**Comment by drGrove** [comment]
Awesome, that's exactly what I was thinking

**Comment by drGrove** [comment]
Do you have something from the go server that already does the checking for weariverse gists? like how does that currently work?

**Comment by bwhite** [comment]
I'll have to implement that part, you can assume the format is just like
what we have from the gist list for the user.

**Comment by bwhite** [comment]
Fixed
