### ISSUE TITLE
shortcuts icon

### ISSUE THREAD

**Issue by drGrove** [lrvick/wearscript-playground#16]
Add a shortcuts icon at the bottom of the menu. By clicking this it should pop up a modal with all of the keyboard shortcuts

**Comment by Kadajett** [comment]
Taking care of it. Looks sexy :facepunch:

**Comment by Kadajett** [comment]
Looks like crap, still a work in progress, but I am going to bed now.
![editorsettingsmodal](https://f.cloud.github.com/assets/3784716/2430579/4518edea-acf1-11e3-90e0-d0649836969c.png)
