### ISSUE TITLE
Grunt go server build is brittle, should probably remove it

### ISSUE THREAD

**Issue by bwhite** [lrvick/wearscript-playground#18]
It doesn't work out of the box and it's easier to just have the user build it if it's not going to work properly.  One issue is that it assumes that your GOPATH is in ~/.go but that's not really reasonable esp if the user installed with a system package.

**Comment by lrvick** [comment]
Yeah that was a quick hack placeholder.

I was actually thinking of replacing that with a call to an included bash script that does checks before doing anything, and creates/uses  ~/.go only if GOPATH is not already set, and installs the modules if they are not already installed etc.

That way it does the right thing, and for users with no prior go setup... it just works.
