### ISSUE TITLE
Add a log tab

### ISSUE THREAD

**Issue by bwhite** [lrvick/wearscript-playground#20]
Some browsers (esp mobile) may not be easy to start the js console.  Having a log tab would be nice for them.  Just like we do for sensors, when on that page update log events.

**Comment by lrvick** [comment]
done.

**Comment by bwhite** [comment]
Log should _only_ log things that come in with the "log" channel.  In the callback that handles it, it should log that data to a LogService which throws away "old" data (maybe store 1000 messages for now).  The purpose of it is so that people who don't have a javascript console (e.g., on mobile) can see their log messages, not to show them angular events.  We can possibly keep this one as a debug mode thing hidden though.

**Comment by lrvick** [comment]
This shows anything that would normally go to to console.log. angular
itself logs nothing. We can use log.log $log.error $log.warn
$log.infoanywhere we want. All logs go to a Logging service for
storage but we only
expose them to the $scope when the log tab is open so... Exactly what you
just described.

Not much in the application is logging ATM but we can use the $log service
to send things there from anywhere we want.

A max number of logs to load to $scope at once could be helpful though
since DOM is less forgiving of loading  10k messages than a real console.
I'll add that.

**Comment by bwhite** [comment]
Yeah I see that is what it does, but it's not what we need.  I need something very specific.  In wearscript you can use WS.log() it sends data over pubsub with [log, message] which we subscribe to.  When we get one of those messages, it should be logged in the logging tab, _nothing_ else at all.

**Comment by lrvick** [comment]
Ah. Well having a real console..log can be useful for actually debugging
network issue or mobile specific issues/bugs s but we could just have only
WS.log be the only thing that uses log.log. We suppress all logs that are
not from $log.log unless debug mode is on in Profile service just like
vim-mode.

That way people only see WS.log stuff except for people that actually want
to see an extended JS console.

Reasonable?
On Mar 16, 2014 10:53 AM, "Brandyn White" notifications@github.com wrote:

Yeah I see that is what it does, but it's not what we need. I need
something very specific. In wearscript you can use WS.log() it sends data
over pubsub with [log, message] which we subscribe to. When we get one of
those messages, it should be logged in the logging tab, _nothing_ else at
all.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/lrvick/wearscript-playground/issues/20#issuecomment-37759077
.

**Comment by bwhite** [comment]
Yeah I think that'd work.  The whole point of WS.log is to act like
someone's console terminal, so they print their own things there to get
feedback.  Dumping a ton of stuff on them would be bad, hiding it behind a
debug flag could be fine for now not sure if it'd fit in that way either
though.  I'd almost say they are just entirely different things and should
be in totally different tabs (this called Debug) and hidden by default.
 But we shouldn't spend time on making the current one make sense just
because it's already there, we should focus on the list we have.

**Comment by lrvick** [comment]
Ok well I can make them separate tabs in like 10 min that only logs Logging.ws which is all by itself. 
Having an extra optional tab makes sense and covers the mobile debugging I was wanting while keeping WS logs totally separate.
