### ISSUE TITLE
Theme Tables

### ISSUE THREAD

**Issue by lrvick** [lrvick/wearscript-playground#22]
Theme tables and stuff to not look bad. See Logging

**Comment by Kadajett** [comment]
## RFC

Do we think that the tables should have different sorting options? I doubt it, but maybe the user would like to sort errors only, or sort by priority. 
![loggingtablesorting](https://f.cloud.github.com/assets/3784716/2430313/32c974b0-accf-11e3-929a-26722bbdde6d.png)

**Comment by Kadajett** [comment]
Made do, decent looking, still RFC though. Export function is pretty cool. 
![loggingsettingawesome](https://f.cloud.github.com/assets/3784716/2430464/820a379e-ace3-11e3-91f5-8db6e1649623.png)
