### ISSUE TITLE
Clicking gears gives 404 (template .html not listed somewhere important?)

### ISSUE THREAD

**Issue by bwhite** [lrvick/wearscript-playground#29]
GET https://api.wearscript.com/unstable/views/modals/settings/editorSettings.html 404 (Not Found)

**Comment by Kadajett** [comment]
Done, Just took out the gear. Not needed for now.

**Comment by Kadajett** [comment]
Will push up before tonight.

**Comment by drGrove** [comment]
i'm using what you have right now. Lance and I are working on something for this already

**Comment by Kadajett** [comment]
What thing? I have completely rewritten this. I just need the hooks.
