### ISSUE TITLE
Canvas Image point to click interface

### ISSUE THREAD

**Issue by drGrove** [lrvick/wearscript-playground#3]
draw image from b64, click one point should work on touch screens and have zoom.

May be bar or buttons

**Comment by bwhite** [comment]
should be settable with a function like (just in terms of params) function setCanvas(imageb64, num_points, callback) where num_points is the required number of points, if that is <= 0 then any number of points can be clicked.  If the value is > 0 then exactly that many points must be clicked.  There should be "reset" and "submit" buttons, on submit send all collected points as a list to the callback like callback([pt0, pt1, ...]).

**Comment by drGrove** [comment]
@bwhite please elaborate some more

**Comment by bwhite** [comment]
It's done
