### ISSUE TITLE
The file selector is disabled in the default script

### ISSUE THREAD

**Issue by bwhite** [lrvick/wearscript-playground#45]
![screen shot 2014-03-20 at 1 15 09 am](https://f.cloud.github.com/assets/14459/2469100/a378068c-afee-11e3-801b-9d69727f74bc.png)

**Comment by drGrove** [comment]
It's disabled if there are no `availableFiles`. Have we considered the notion of just making the example script a gist? and pulling that in every time. Since forking now exists and @lrvick is almost done with auto-saving?

**Comment by bwhite** [comment]
We could but forking doesn't work reliably yet.  The dropdown seems to stay
disabled even if there are files

**Comment by bwhite** [comment]
Tested with new code, still doesn't work

**Comment by lrvick** [comment]
fixed in develop
