### ISSUE TITLE
Pretty Table for Sensors

### ISSUE THREAD

**Issue by drGrove** [lrvick/wearscript-playground#7]
Pretty table for sensors
Graphing JS for graphing sensor data

**Comment by bwhite** [comment]
I have some code in the old playground to do the graphing and in the logviz thing so I'll probably do the actual graphing.  The table should just keep a consistent ordering and be all pretty like.  Previous sensor table https://github.com/wearscript/wearscript-android/blob/730a7c70e79ef5fb27ec77c8a01d5b0c890a96bb/server/js/playground.js#L141
