### ISSUE TITLE
Guided Tour

### ISSUE THREAD

**Issue by drGrove** [lrvick/wearscript-playground#8]
a getting started tutorial and device setup

--edit--
A guided tour of the editor. Device setup has moved to modal

**Comment by bwhite** [comment]
For this I'm thinking do exactly this https://glass.google.com/u/0/setup and I'll make any videos we need for it.

**Comment by Kadajett** [comment]
What about this? http://bootstraptour.com/

I believe there is already an angular verison of this in existence also!

**Comment by bwhite** [comment]
Sure that'd be cool.  It's a bit more all over the place than I had in mind but the benefit is that we just have one consistent thing and get them acclimated quickly.

**Comment by drGrove** [comment]
@coryk135  --> http://ngmodules.org/modules/angular-intro.js
you have one job.

**Comment by bwhite** [comment]
That's pretty cool, can it also change the tabs, open up the setup modal,
etc?

**Comment by drGrove** [comment]
I would assume so. I'm sure you could make people click on things and such. Cory is going to work on this in his own branch and we'll test it heavily before merging it. We know the IDE very well because we're programming it. Noobs may have issues. So this should definitely be ready for MIT

**Comment by coryk135** [comment]
I accidentally found another one we could use. It seems to be slightly more popular. So between angular-intro.js and angular-tour which one would you guys prefer? https://github.com/DaftMonk/angular-tour

**Comment by coryk135** [comment]
Danny and I agreed on angular-intro because it will isolate elements on the page.

**Comment by bwhite** [comment]
I think I like the angular-tour better though I'm not sure how with either
of them we can support opening modals, etc.  Should be possible using the
callbacks.

**Comment by bwhite** [comment]
Ok cool
