### ISSUE TITLE
File Manager (New Gist View)

### ISSUE THREAD

**Issue by drGrove** [lrvick/wearscript-playground#9]
File select drop down in editor

**Comment by bwhite** [comment]
Anytime the editor is shown we should have the dropdown, otherwise it shouldn't.  The editor service should hold the state for all files including dropdown state so we recreate everything properly.

**Comment by lrvick** [comment]
So this dropdown should essentially just be the same content as the gists tab? So we even need the gists tab once this is added?

Or is this instead just a list of files within a particular gist?

**Comment by lrvick** [comment]
Or! is this just the actions for this file, thus "save to gist, execute line, run script" with key commands beside them etc?
